### ISSUE TITLE
Template Issue

### ISSUE THREAD

**Issue by IsaiasUziel** [IsaiasUziel/xkcd-app#2]
## Descripción del Issue
[Describe aquí en qué consiste el issue de manera clara y concisa.]

## Prioridad
[Indica la prioridad del issue. Puedes usar etiquetas como "Alta", "Media" o "Baja", o crear un sistema de puntuación.]

## Estado
[Indica el estado actual del issue. Puedes usar etiquetas como "Abierto", "En Progreso", "Revisión" o "Completado".]

## Tareas
- [ ] Tarea 1
- [ ] Tarea 2
- [ ] Tarea 3

## Responsable
[Indica quién es el responsable de este issue.]

## Fecha Límite
[Indica la fecha límite para completar este issue si es aplicable.]

## Criterios de Aceptación
- [ ] Criterio 1: [Descripción de lo que significa que este issue está completado.]
- [ ] Criterio 2: [Descripción de otro criterio de aceptación.]

## Comentarios Adicionales
[Agrega cualquier comentario o información adicional que pueda ser relevante para este issue.]

## Asignar etiquetas
[Asigna etiquetas que ayuden a categorizar este issue, como "bug", "mejora", "documentación", etc.]

## Enlaces relacionados
[Agrega enlaces a otros recursos relacionados con este issue, como enlaces a PRs, documentos, etc.]

**Comment by waldoignacio** [comment]
Comentarios de Waldo

**Comment by IsaiasUziel** [comment]
oye no poh xd
